# Generated by Django 4.0.4 on 2022-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indiceperiodo',
            name='periodo_mes',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=7, verbose_name='Mês do Período'),
        ),
    ]
