# Generated by Django 4.0.4 on 2022-05-20 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoFgts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(blank=True, max_length=50)),
                ('arquivo_extrato', models.FileField(upload_to='uploaded_account_statement/%Y/%m/%d/')),
                ('empregador', models.CharField(blank=True, max_length=50)),
                ('juros_anual', models.IntegerField(blank=True, choices=[(3, '3%'), (6, '6%')], default=3)),
                ('valor_causa', models.FloatField(blank=True, editable=False)),
                ('inicio_periodo', models.DateField(blank=True, editable=False)),
                ('termino_periodo', models.DateField(blank=True, editable=False)),
                ('user', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
