# Generated by Django 4.0.4 on 2022-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_calculofgts_hide_alter_calculofgts_arquivo_extrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofgts',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
