# Generated by Django 4.0.4 on 2022-05-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0004_calculofgts_df_html_alter_calculofgts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculofgts',
            name='df_json',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
