# Generated by Django 4.0.4 on 2022-07-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0005_calculofgts_df_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculofgts',
            name='df_html',
        ),
        migrations.AlterField(
            model_name='calculofgts',
            name='df_json',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='calculofgts',
            name='pago',
            field=models.BooleanField(default=True),
        ),
    ]
